# docker-compose.yml
version: "3.8"

networks:
  raidleader:
    name: raidleader

services:
  server:
    image: "us-east4-docker.pkg.dev/rlio-production/rlio-production-docker/py-fapi-gql:production"
    container_name: raidleader_gql
    build:
      context: .
      args:
        DB_SYNC_DSN: "postgresql+psycopg2://${DB_URL}"
        DB_DSN: "postgresql+asyncpg://${DB_URL}"
    hostname: raidleader_gql
    networks:
      - raidleader
    ports:
      - "8000:8000"
    restart: always
