# docker-compose.yml
version: "3.8"

networks:
  raidleader:
    name: raidleader

services:
  server:
    image: "us-east4-docker.pkg.dev/rlio-production/rlio-production-docker/py-fapi-gql:dev"
    container_name: raidleader_gql
    build:
      context: .
      args:
        DB_SSL_AUTH: 1
    hostname: raidleader_gql
    networks:
      - raidleader
    ports:
      - "8000:8000"
    restart: always
    environment:
      - PORT=8000
