name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create .env
        run: echo 'DB_DSN="${{ secrets.CLOUD_SQL_DSN }}"' >> .env
      # BEGIN - Create cert files
      - name: Write Certs
        run: |-
          mkdir -p ./.certs
          echo "${{ secrets.CLOUD_SQL_CLIENT_CERT }}" >> .certs/client.pem
          echo "${{ secrets.CLOUD_SQL_CLIENT_KEY }}" >> .certs/key.pem
          echo "${{ secrets.CLOUD_SQL_SERVER_CA }}" >> .certs/sa.pem
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag "michaelfay/raidleader_gql:$GITHUB_SHA"
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Publish image to Docker Hub
        run: docker push "michaelfay/raidleader_gql:$GITHUB_SHA"
