name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create .env
        run: echo 'DB_DSN="${{ secrets.DEV_DB_DSN }}"' >> .env
      - name: Build the Docker image
        run: |-
          docker build .  --build-arg DB_DSN="${{ secrets.DEV_DB_DSN }}" --file dev.Dockerfile "michaelfay/raidleader_gql:$GITHUB_SHA" ./
          docker image tag "michaelfay/raidleader_gql:$GITHUB_SHA" "michaelfay/raidleader_gql:latest"
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Publish image to Docker Hub
        run: |-
          docker push "michaelfay/raidleader_gql:$GITHUB_SHA"
          docker push "michaelfay/raidleader_gql:latest"
